[tool.mypy]
follow_imports = "silent"
warn_return_any = false
ignore_missing_imports = true
exclude = 'venv|\.env|\.venv|\.tox|dist|build'

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
known_first_party = "taxisim"
force_single_line = true
atomic = true
balanced_wrapping = true
include_trailing_comma = true
combine_as_imports = true
use_parentheses = true

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:"]
